#!/bin/bash
echo Backing up /public/uploads directory.
mkdir ~/bkupMedia
cp -r ../myCMS/public/uploads/* ~/bkupMedia/
echo Removing old myCMS directory...
rm -rf ../myCMS/
echo Copying Keystone v0.4 files...
cp -r ../keystone4/ ../myCMS
echo Keystone v0.4 Copied to myCMS

echo Copying the server settings files if they exist
cp ../myCMS/private/privatesettings.json ~
cp ../myCMS/public/js/publicsettings.json ~