#!/bin/bash
echo Preparing to copy ConnextCMS files...

echo Copying Keystone core files...
cp keystone-files/api.js ../myCMS/node_modules/keystone/lib/middleware/
cp keystone-files/base.jade ../myCMS/node_modules/keystone/templates/layout/base.jade
cp keystone-files/keystone.js ../myCMS/

echo Copying Keystone Models...
cp models/*.js ../myCMS/models/

echo Copying Keystone Templates...
cp templates/views/*.hbs ../myCMS/templates/views/
cp templates/views/helpers/*.js ../myCMS/templates/views/helpers/
cp templates/views/layouts/*.hbs ../myCMS/templates/views/layouts/

echo Copying Keystone Routes...
cp routes/index.js ../myCMS/routes/
mkdir ../myCMS/routes/api
cp routes/api/*.js ../myCMS/routes/api/
cp routes/views/* ../myCMS/routes/views/

echo Copying Keystone Public directory...
cp public/*.html ../myCMS/public/

echo ...creating uploads directory...
mkdir ../myCMS/public/uploads
mkdir ../myCMS/public/uploads/images
mkdir ../myCMS/public/uploads/files

echo ...copying fonts...
cp public/fonts/font* ../myCMS/public/fonts/
cp public/fonts/Font* ../myCMS/public/fonts/

echo ...copying images...
cp public/images/*.jpg ../myCMS/public/images/
cp public/images/*.png ../myCMS/public/images/
cp public/images/*.gif ../myCMS/public/images/
cp public/images/*.svg ../myCMS/public/images/

echo ...copying javascript files...
cp public/js/*.js ../myCMS/public/js/
cp -r public/js/app ../myCMS/public/js/
cp -r public/js/lib ../myCMS/public/js/

echo ...copying styles...
cp -r public/styles/fonts ../myCMS/public/styles/
cp -r public/styles/skins ../myCMS/public/styles/
cp public/styles/*.css ../myCMS/public/styles/
cp public/styles/*.map ../myCMS/public/styles/

echo Do not forget to update your server IP address in myCMS/public/js/app/main_dashboard_app.js
